### ISSUE TITLE
[Linux] no display patch

### ISSUE THREAD

**Issue by ShiroiKuma** [mifki/df-twbt#28]
I've installed the current DFHack (dfhack-0.40.24-r3-Linux-gcc-4.5.tar.bz2) on my system which works fine. I've then copied the latest TWBT (twbt-5.44-linux) and placed the .so files into my ./hack/plugins folder.

My init file contains the following:
````
[FONT:text_12x16.png]
[FULLFONT:text_12x16.png]

[GRAPHICS:YES]
[GRAPHICS_WINDOWEDX:0]
[GRAPHICS_WINDOWEDY:0]
[GRAPHICS_FONT:ironhand16.png]
[GRAPHICS_FULLSCREENX:0]
[GRAPHICS_FULLSCREENY:0]
[GRAPHICS_FULLFONT:ironhand16.png]
[GRAPHICS_BLACK_SPACE:YES]

[PRINT_MODE:TWBT]
````

However when I run ````dfhack```` to start my game I get the following output in my console.

````
Loading bindings from data/init/interface.txt
Resetting textures
Can't load plugin /opt/dwarf-fortress/hack/plugins/mousequery.plug.so
TWBT: version 5.44
TWBT: no display patch
reshape_graphics
Can't load plugin /opt/dwarf-fortress/hack/plugins/resume.plug.so
Can't load plugin /opt/dwarf-fortress/hack/plugins/automaterial.plug.so
reshape_graphics
reshape_graphics
...
Cannot enable plugin: automaterial
Cannot enable plugin: mousequery
Cannot enable plugin: resume
````
The game starts however and appears to be using my seperate png for the fonts on main menu and in the arena okay. And when I shut down I get the following error in console too.

````
Plugin twbt has failed to shutdown!
````

Is there anything else I can provide to help with this issue?
Is the no display patch a warning or message? (it's yellow so assuming warning vs error)
What could be causing the others to error? (Though to be honest I only wanted twbt, no sure what they are yet :-) )

**Comment by pronvit** [comment]
Sorry I don't understand, do you have any issues actually? The 'no display patch' message itself is not an error. The real problem is that some plugins didn't load, this should be fixed in version 5.45 (http://build.mifki.com)

**Comment by elariah** [comment]
It looked okay in Testing Arena, but when I see red/yellow text like that on starting any application I got a little concerned that there is a issue, so haven't made my main world yet.

I looked at the code and it look liked it would ALWAYS show that message on a Linux system due to a define within the if-else block. So I am curious, what does it mean? Does it mean that I don't need the patch due to running Linux.

I can guess mousequery is a multilevel compatible version to see K item viewing with mouse and multilevel But what's automaterial and resume? What am I missing by them not being loaded by twbt? Should I just delete them?

And lastly, the final error about not twbt failing to shut down. Is that also not an actual error?

**Comment by elariah** [comment]
I'll check 5.45 after my planes lands and see if that fixes it anyway.

**Comment by lethosor** [comment]
> Does it mean that I don't need the patch due to running Linux.

From what I understand, it means that the patch isn't located for Linux, so TwbT falls back to an alternative method.

automaterial, mousequery, and resume are three standard DFHack plugins which TwbT distributes modified versions of. Which versions of those plugins are you using (the ones provided by DFHack or TwbT)?

**Comment by pronvit** [comment]
That are just more of my debug msgs that nobody likes, ignore them. I've fixed automaterial, mousequery, and resume plugins in the latest build.
